######################################################################
# Automatically generated by qmake (2.01a) Mon May 14 18:50:02 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += diagramwindow.h link.h node.h propertiesdialog.h
FORMS += propertiesdialog.ui
SOURCES += diagramwindow.cpp link.cpp main.cpp node.cpp propertiesdialog.cpp
RESOURCES += resources.qrc
