######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 20 21:28:49 2018
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    flowchartsymbolpicker.cpp

HEADERS += \
    flowchartsymbolpicker.h

RESOURCES += \
    flowchartsymbolpicker.qrc
