######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 20:53:52 2019
######################################################################
QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QT += opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    vowelcube.cpp

HEADERS += \
    vowelcube.h
