######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 21 13:20:34 2018
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += oventimer.h
SOURCES += main.cpp oventimer.cpp
