######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 17 21:01:05 2018
######################################################################
QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QT += opengl

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    tetrahedron.cpp

HEADERS += \
    tetrahedron.h
