######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 4 18:26:40 2019
######################################################################
QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QT += opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    teapots.cpp

HEADERS += \
    teapots.h
