######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 22 20:07:52 2018
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    coordinatesetter.cpp

HEADERS += \
    coordinatesetter.h
