######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 25 21:12:26 2018
######################################################################
QT += core gui

greaterThan(QT_MAJOR_VERSION, 4) : QT +=widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    citymodel.cpp

HEADERS += \
    citymodel.h
